# Generated by Django 5.1.1 on 2025-01-24 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='idbox',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(
            name='appointment',
            table='Appointment',
        ),
    ]
